import './assets/template/vendor/jquery-3.2.1.min.js'
import  './assets/template/vendor/jquery-3.2.1.min.js'
import  './assets/template/vendor/bootstrap-4.1/popper.min.js'
import  './assets/template/vendor/bootstrap-4.1/bootstrap.min.js'
import  './assets/template/vendor/slick/slick.min.js'
import  './assets/template/vendor/wow/wow.min.js'
import  './assets/template/vendor/animsition/animsition.min.js'
import  './assets/template/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js'
import  './assets/template/vendor/counter-up/jquery.waypoints.min.js'
import  './assets/template/vendor/counter-up/jquery.counterup.min.js'
import  ' ./assets/template/vendor/circle-progress/circle-progress.min.js'
import  './assets/template/vendor/perfect-scrollbar/perfect-scrollbar.js'
import  './assets/template/vendor/chartjs/Chart.bundle.min.js'
import  './assets/template/vendor/select2/select2.min.js'
import './assets/template/js/main.js' 